[PARSER]
    Name        jsonparser
    Format      json
    Time_Key    time
    Time_Keep   On

[PARSER]
    Name        wso2apim_carbon_parser
    Format      regex
    Regex       ^(?<log_type>[A-Z]+) \[(?<time>[0-9-]{10} [0-9:,]{12})\]\s+(?<level>[A-Z]+)\s+\{(?<module>[^}]+)\}\s*(?:\[\s*Deployed From Artifact Container:\s+(?<package>[^\]]+)\s*\]\s*)?\s*(?:-\s+\{api:(?<api>[^}]+)\})?\s*(?<message>(.|\n)+)
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S,%L

[MULTILINE_PARSER]
    name          wso2_multiline_parser
    type          regex
    flush_timeout 1000
    rule          "start_state"   "^CARBON.*"   "cont"
    rule          "cont"          "^(?!CARBON|CREL|AUDIT|HTTP|TRACE|METRIC).*" "cont"